# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCourse', models.IntegerField(unique=True)),
                ('Name', models.TextField(max_length=255)),
                ('Duration', models.TextField(max_length=255)),
                ('Teacher', models.TextField(max_length=255)),
                ('Value', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Fight',
        ),
    ]
