# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161228_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComment', models.IntegerField(unique=True)),
                ('Course', models.TextField(max_length=255)),
                ('Text', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
        migrations.DeleteModel(
            name='Boxer',
        ),
    ]
